#!/system/bin/sh

LOG_FILE_PATH="/data/local/tmp/set_bluetooth.log"
AGENT_LOG_GILE_PATH="/data/local/tmp/agent.log"
PASSWORD=0731

function addLog() { # 로그 기록
    local MESSAGE="$1"
    local CURRENT_TIME=$(date +"%Y.%m.%d-%H.%M.%S")
    echo "[$CURRENT_TIME] $MESSAGE" >> "$LOG_FILE_PATH"
}

# : > "$LOG_FILE_PATH" # 로그파일 초기화

# 부팅 완료 되었는지 확인
if [ "$(getprop sys.boot_completed)" != "1" ]; then
    addLog "[SKIP] 아직 부팅 완료 아님 -> 종료"
    exit 0
fi

# 블루투스 USB 동글이 꼽힐때 까지(hci0가 생성될 때까지) 대기
if ! hciconfig | grep -q hci0; then
    addLog "[SKIP] hci0 없음. USB 블루투스 동글 미삽입 상태 -> 종료"
    exit 0
fi

# hci0가 이미 활성 상태인지 체크
if hciconfig hci0 | grep -q "UP RUNNING"; then
    addLog "[SKIP] hci0 이미 활성 상태. 별도 작업 안 함 -> 종료"
    exit 0
fi

addLog "[ACTION] hci0 탐지됨. 블루투스 초기화 시작"

# 이전 agent 프로세스 종료
ps | grep '[a]gent' | while read line; do
    pid=$(echo $line | awk '{print $2}')
    addLog "[KILL] 기존 agent 종료: PID $pid"
    kill -9 "$pid"
done

hciconfig hci0 down
sleep 2
hciconfig hci0 up
sleep 2
hciconfig hci0 piscan

addLog "[ACTION] 블루투스 초기화 끝"

## agent 실행
#if [ -x /system/xbin/agent ]; then
#    /system/xbin/agent --adapter hci0 "$PASSWORD" >> "$AGENT_LOG_GILE_PATH" 2>&1 &
#    addLog "[START] agent 실행 완료"
#else
#    addLog "[ERROR] agent 실행 파일 없음"
#fi